# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thanos < Formula
  desc "LOOP AI - Design, Code, Review, Test"
  homepage "https://github.com/tinhtran24/thanos"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tinhtran24/thanos/releases/download/v1.0.4/thanos_1.0.4_darwin_amd64.tar.gz"
      sha256 "c73e61216e4c8c2065db38a624d797f719dc3e5c648e4b074485d13d38298751"

      define_method(:install) do
        bin.install "thanos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tinhtran24/thanos/releases/download/v1.0.4/thanos_1.0.4_darwin_arm64.tar.gz"
      sha256 "50adce374496875c3a24b29dbd6adae91d17b3871c21ba9d55cad9f2ae1bf3e7"

      define_method(:install) do
        bin.install "thanos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tinhtran24/thanos/releases/download/v1.0.4/thanos_1.0.4_linux_amd64.tar.gz"
      sha256 "959cd433519c1f53fe15935aadded572ea816ad1655e3673e4c26b9e99ddadb2"
      define_method(:install) do
        bin.install "thanos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tinhtran24/thanos/releases/download/v1.0.4/thanos_1.0.4_linux_arm64.tar.gz"
      sha256 "9fb7b58dade507e8c8f4ab96ddb469067d527655351a45c03117db61b9220a56"
      define_method(:install) do
        bin.install "thanos"
      end
    end
  end

  test do
    system "#{bin}/thanos", "--version"
  end
end
