# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thanos < Formula
  desc "LOOP AI - Design, Code, Review, Test"
  homepage "https://github.com/tinhtran24/thanos"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tinhtran24/thanos/releases/download/v2.0.0/thanos_2.0.0_darwin_amd64.tar.gz"
      sha256 "69072be5da740823622aabbf8573085832005e55795b87f9237e906305d62d07"

      define_method(:install) do
        bin.install "thanos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tinhtran24/thanos/releases/download/v2.0.0/thanos_2.0.0_darwin_arm64.tar.gz"
      sha256 "5c1839e796c28e8ab344359e92be3cafeebd9590b89b9139922d24e1c5ca86b0"

      define_method(:install) do
        bin.install "thanos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tinhtran24/thanos/releases/download/v2.0.0/thanos_2.0.0_linux_amd64.tar.gz"
      sha256 "45bddfd1bc0cd3e5bf27e1071ad1c52820f90c64d5698d311c0def5eb32e6585"
      define_method(:install) do
        bin.install "thanos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tinhtran24/thanos/releases/download/v2.0.0/thanos_2.0.0_linux_arm64.tar.gz"
      sha256 "0a8f679d992c8161e4649a6376c2ca4a2a3c0bc8044eb63c77b3515ca0085923"
      define_method(:install) do
        bin.install "thanos"
      end
    end
  end

  test do
    system "#{bin}/thanos", "--version"
  end
end
